#AndroidIDE: enforce UTF-8 & locale for Gradle daemon
#Mon Jan 05 08:22:10 GMT 2026
systemProp.user.language=en
systemProp.user.country=US
systemProp.sun.jnu.encoding=UTF-8
systemProp.file.encoding=UTF-8
org.gradle.jvmargs=-Xmx4608m -Dfile.encoding\=UTF-8
android.useAndroidX=true
android.enableR8.fullMode=true
